events {}

http {
  upstream auth_service {
    server auth-service:4000;
  }

  upstream media_service {
    server media-service:5000;
  }

  server {
    listen 80;

    location /auth {
      proxy_pass http://auth_service;
    }

    location /media {
      proxy_pass http://media_service;
    }
  }
}
