import type { EditorProject } from '../../types/editor.types'
import type { TimelineClip } from '../../types/clip.types'
import type { TimelineTrack } from '../../types/track.types'
import {
  CLIP_COLORS,
  TRACK_HEIGHT_AUDIO,
  TRACK_HEIGHT_EFFECT,
  TRACK_HEIGHT_TEXT,
  TRACK_HEIGHT_VIDEO,
} from './timelineConstants'

export const mockTimelineClips: TimelineClip[] = [
  {
    id: 'mock-video-intro',
    trackId: 'track-video-1',
    type: 'video',
    name: 'Intro clip',
    startTime: 0,
    duration: 8,
    trimStart: 0,
    trimEnd: 8,
    color: CLIP_COLORS.video,
  },
  {
    id: 'mock-video-main',
    trackId: 'track-video-1',
    type: 'video',
    name: 'Main clip',
    startTime: 8,
    duration: 20,
    trimStart: 0,
    trimEnd: 20,
    color: CLIP_COLORS.video,
  },
  {
    id: 'mock-video-broll',
    trackId: 'track-video-1',
    type: 'video',
    name: 'B-roll clip',
    startTime: 31,
    duration: 12,
    trimStart: 0,
    trimEnd: 12,
    color: CLIP_COLORS.video,
  },
  {
    id: 'mock-audio-bg',
    trackId: 'track-audio-1',
    type: 'audio',
    name: 'Background audio',
    startTime: 0,
    duration: 45,
    trimStart: 0,
    trimEnd: 45,
    color: CLIP_COLORS.audio,
  },
  {
    id: 'mock-audio-vo',
    trackId: 'track-audio-1',
    type: 'audio',
    name: 'Voiceover',
    startTime: 10,
    duration: 15,
    trimStart: 0,
    trimEnd: 15,
    color: CLIP_COLORS.audio,
  },
  {
    id: 'mock-text-title',
    trackId: 'track-text-1',
    type: 'text',
    name: 'Title text',
    startTime: 1,
    duration: 4,
    trimStart: 0,
    trimEnd: 4,
    color: CLIP_COLORS.text,
  },
  {
    id: 'mock-text-lower-third',
    trackId: 'track-text-1',
    type: 'text',
    name: 'Lower third',
    startTime: 12,
    duration: 5,
    trimStart: 0,
    trimEnd: 5,
    color: CLIP_COLORS.text,
  },
  {
    id: 'mock-effect-fade',
    trackId: 'track-effect-1',
    type: 'effect',
    name: 'Fade in',
    startTime: 0,
    duration: 2,
    trimStart: 0,
    trimEnd: 2,
    color: CLIP_COLORS.effect,
  },
  {
    id: 'mock-effect-blur',
    trackId: 'track-effect-1',
    type: 'effect',
    name: 'Blur effect',
    startTime: 18,
    duration: 6,
    trimStart: 0,
    trimEnd: 6,
    color: CLIP_COLORS.effect,
  },
]

export function createMockTracks(): TimelineTrack[] {
  return [
    {
      id: 'track-video-1',
      name: 'Video Track 1',
      type: 'video',
      height: TRACK_HEIGHT_VIDEO,
      isLocked: false,
      isMuted: false,
      isVisible: true,
      clips: mockTimelineClips.filter((clip) => clip.trackId === 'track-video-1'),
    },
    {
      id: 'track-audio-1',
      name: 'Audio Track 1',
      type: 'audio',
      height: TRACK_HEIGHT_AUDIO,
      isLocked: false,
      isMuted: false,
      isVisible: true,
      clips: mockTimelineClips.filter((clip) => clip.trackId === 'track-audio-1'),
    },
    {
      id: 'track-text-1',
      name: 'Text Track 1',
      type: 'text',
      height: TRACK_HEIGHT_TEXT,
      isLocked: false,
      isMuted: false,
      isVisible: true,
      clips: mockTimelineClips.filter((clip) => clip.trackId === 'track-text-1'),
    },
    {
      id: 'track-effect-1',
      name: 'Effects Track 1',
      type: 'effect',
      height: TRACK_HEIGHT_EFFECT,
      isLocked: false,
      isMuted: false,
      isVisible: true,
      clips: mockTimelineClips.filter((clip) => clip.trackId === 'track-effect-1'),
    },
  ]
}

export function createMockEditorProject(): EditorProject {
  return {
    id: 'mock-editor-project',
    title: 'StreamForge Demo Timeline',
    duration: 60,
    width: 1920,
    height: 1080,
    fps: 30,
    tracks: createMockTracks(),
    mediaAssetIds: [],
    projectSettings: {
      aspectRatio: '16:9',
      resolution: {
        width: 1920,
        height: 1080,
      },
      fps: 30,
      backgroundColor: '#000000',
    },
    renderSettings: {
      format: 'mp4',
      quality: 'standard',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
}
